# Generated by Django 5.2 on 2025-05-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Schueler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vorname", models.CharField(max_length=50)),
                ("nachname", models.CharField(max_length=50)),
                ("klasse", models.CharField(max_length=10)),
                ("anwesend", models.BooleanField(default=False)),
            ],
        ),
    ]
